name: CI

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache clang
        id: cache-clang
        uses: actions/cache@v3
        with:
          path: clang-cache
          key: ${{ runner.os }}-cache-clang

      - name: Download Kuribo-Clang
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          mkdir clang-cache
          cd clang-cache
          wget -O ClangKuribo.tar.gz https://www.dropbox.com/s/a5ds6eejbnwvo39/ClangKuribo.tar.gz?dl=1
          cd ..
  
      - name: Configure Tools
        run: |
          cd clang-cache
          tar -xf ClangKuribo.tar.gz
          mv ClangKuribo ../clang
          cd ..
          tar -xf dkp-cache/devkitPPC-r41-2-linux_x86_64.pkg.tar.xz
          sudo cp -r opt /
          sudo apt-get install libboost-all-dev
      
      - name: elf2rel Cache
        id: cache-elf2rel
        uses: actions/cache@v3
        with:
          path: elf2rel-cache
          key: ${{ runner.os }}-cache-e2r

      - name: Configure cmake
        if: steps.cache-elf2rel.outputs.cache-hit != 'true'
        uses: jwlawson/actions-setup-cmake@v1.13

      - name: Make elf2rel
        if: steps.cache-elf2rel.outputs.cache-hit != 'true'
        run: |
          mkdir elf2rel-cache
          cd elf2rel-cache
          cmake ../elf2rel
          make
          cd ..
          


      - name: Build Rels
        run: |
          cp elf2rel-cache/elf2rel elf2rel/elf2rel
          make

      - name: Upload Result
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: bin/*.rel
        
